- id: '1610996669564'
  alias: lights on when paused
  description: 'Bring lights up to 50% when media is paused on Shield'
  trigger:
  - platform: state
    for: '2'
    entity_id: media_player.theater_shield
    from: playing
    to: paused
  condition:
  - condition: state
    entity_id: light.theater_lights
    state: 'off'
  action:
  - service: light.turn_on
    data:
      entity_id: light.theater_lights
      brightness_pct: 50
      transition: 1
  mode: single
- id: '1610996991686'
  alias: lights off on play
  description: 'Turn off lights when Media begins to play'
  trigger:
  - platform: state
    entity_id: media_player.theater_shield
    to: playing
  condition: []
  action:
  - service: light.turn_off
    data:
      entity_id: light.theater_lights
      transition: 1
  - service: light.turn_off
    data:
      entity_id: light.theater_overhead
      transition: 1
  mode: single
- id: '1611024383994'
  alias: lights up on stop
  description: 'Bring lights up to 100% when media is stopped'
  trigger:
  - platform: state
    entity_id: media_player.plex_plex_for_android_tv_shield_android_tv
    for: '2'
  condition:
  - condition: device
    device_id: 7d8e57e35efd5221948d06915e934a4c
    domain: media_player
    entity_id: media_player.plex_plex_for_android_tv_shield_android_tv
    type: is_idle
  - condition: not
    conditions:
    - condition: device
      device_id: 7d8e57e35efd5221948d06915e934a4c
      domain: media_player
      entity_id: media_player.plex_plex_for_android_tv_shield_android_tv
      type: is_playing
    - condition: device
      device_id: 7d8e57e35efd5221948d06915e934a4c
      domain: media_player
      entity_id: media_player.plex_plex_for_android_tv_shield_android_tv
      type: is_paused
  action:
  - service: light.turn_on
    data:
      entity_id: light.theater_lights
      transition: 2
  mode: single
