- id: '1610996669564'
  alias: lights on when paused
  description: Turn on Ambient light on Pause
  trigger:
  - platform: state
    entity_id: media_player.theater_shield
    from: playing
    to: paused
  condition: []
  action:
  - type: turn_on
    device_id: 3e79f994a8b002350491947d33bbb1e5
    entity_id: switch.theater_ambient
    domain: switch
  mode: single
- id: '1610996991686'
  alias: lights off on play
  description: Turn off lights when Media begins to play
  trigger:
  - platform: state
    entity_id: media_player.theater_shield
    to: playing
  condition: []
  action:
  - type: turn_off
    device_id: f12a835a0faa13cb4826f7d38223a344
    entity_id: light.theater_lights_2
    domain: light
  - type: turn_off
    device_id: 3e79f994a8b002350491947d33bbb1e5
    entity_id: switch.theater_ambient
    domain: switch
  mode: single
- id: '1611024383994'
  alias: lights up on stop or idle
  description: Bring lights up to 100% when media is stopped
  trigger:
  - platform: state
    entity_id: media_player.theater_shield
    to: idle
  - platform: state
    entity_id: media_player.theater_shield
    to: 'off'
  condition:
  - condition: not
    conditions:
    - condition: device
      device_id: 7d8e57e35efd5221948d06915e934a4c
      domain: media_player
      entity_id: media_player.plex_plex_for_android_tv_shield_android_tv
      type: is_playing
    - condition: state
      entity_id: media_player.theater_shield
      state: paused
  action:
  - type: turn_on
    device_id: f12a835a0faa13cb4826f7d38223a344
    entity_id: light.theater_lights_2
    domain: light
    brightness_pct: 100
  mode: single
- id: '1612398301259'
  alias: lights on during Standby
  description: Turn on Ambient light on Standby
  trigger:
  - platform: state
    entity_id: media_player.theater_shield
    from: playing
    to: standby
  condition: []
  action:
  - type: turn_on
    device_id: 3e79f994a8b002350491947d33bbb1e5
    entity_id: switch.theater_ambient
    domain: switch
  mode: single
- id: '1613889538573'
  alias: set night at 10p
  description: ''
  trigger:
  - platform: time
    at: '22:00:00'
  condition: []
  action:
  - scene: scene.night_time
  - service: hue.hue_activate_scene
    data:
      group_name: master
      scene_name: nightlight
  mode: single
- id: '1618764535146'
  alias: Roon in the Office
  description: ''
  trigger:
  - platform: device
    device_id: eb407f8314ed005bf11f3aaa09cbdc8c
    domain: media_player
    entity_id: media_player.office_roonberry
    type: playing
  condition: []
  action:
  - service: media_player.turn_on
    target:
      entity_id: media_player.office_main
  - service: media_player.select_source
    target:
      entity_id: media_player.office_main
    data:
      source: optical
  mode: single
- id: '1618778013049'
  alias: lights off on plex play
  description: ''
  trigger:
  - platform: device
    device_id: b98ccd3b931bd8464397902820797d40
    domain: media_player
    entity_id: media_player.plex_plex_for_android_tv_shield_android_tv
    type: playing
  condition: []
  action:
  - type: turn_off
    device_id: f12a835a0faa13cb4826f7d38223a344
    entity_id: light.theater_lights_2
    domain: light
  - type: turn_off
    device_id: 3e79f994a8b002350491947d33bbb1e5
    entity_id: switch.theater_ambient
    domain: switch
  mode: single
- id: '1618778083115'
  alias: ambient light on plex pause
  description: ''
  trigger:
  - platform: device
    device_id: b98ccd3b931bd8464397902820797d40
    domain: media_player
    entity_id: media_player.plex_plex_for_android_tv_shield_android_tv
    type: paused
  condition:
  - condition: device
    type: is_off
    device_id: f12a835a0faa13cb4826f7d38223a344
    entity_id: light.theater_lights_2
    domain: light
  action:
  - type: turn_on
    device_id: 3e79f994a8b002350491947d33bbb1e5
    entity_id: switch.theater_ambient
    domain: switch
  mode: single
- id: '1626916974326'
  alias: Turn on Stereo when Roon starts playing
  description: ''
  trigger:
  - platform: device
    device_id: df15dcd28b7a749101bec9812d91292f
    domain: media_player
    entity_id: media_player.family_room_stereo
    type: playing
  condition: []
  action:
  - service: media_player.turn_on
    target:
      entity_id: media_player.family_room_main
  - service: media_player.select_source
    target:
      entity_id: media_player.family_room_main
    data:
      source: audio3
  - service: media_player.volume_set
    data:
      volume_level: 0.45
    target:
      entity_id: media_player.family_room_main
  mode: single
- id: '1626918072532'
  alias: Roon - Turn on Theater
  description: ''
  trigger:
  - platform: device
    device_id: 14b1a9a958af9876e0dc5087c0940622
    domain: media_player
    entity_id: media_player.theater_roonberry
    type: playing
  condition:
  - condition: device
    type: is_off
    device_id: ba50c7a4ef3fb16920ace270971155f2
    entity_id: switch.theater_remote_play_ps4
    domain: switch
  action:
  - type: turn_on
    device_id: ba50c7a4ef3fb16920ace270971155f2
    entity_id: switch.theater_remote_listen_to_roon
    domain: switch
  mode: single
- id: '1627081584215'
  alias: Turn on mcRack when Roon plays
  description: ''
  trigger:
  - platform: device
    device_id: dd73ebe3c390d6beffb825ee27773501
    domain: media_player
    entity_id: media_player.mcrack
    type: playing
  condition: []
  action:
  - type: turn_on
    device_id: ba50c7a4ef3fb16920ace270971155f2
    entity_id: switch.theater_remote_manage_mediacenter
    domain: switch
  mode: single
- id: '1627081645075'
  alias: Turn off stereo when mcrack stops playing
  description: ''
  trigger:
  - platform: device
    device_id: dd73ebe3c390d6beffb825ee27773501
    domain: media_player
    entity_id: media_player.mcrack
    type: turned_off
  condition: []
  action:
  - type: turn_off
    device_id: ba50c7a4ef3fb16920ace270971155f2
    entity_id: switch.theater_remote_manage_mediacenter
    domain: switch
  mode: single
- id: '1627081929300'
  alias: Turn off Stereo when Roon Stops playing
  description: Auto off in Family Room
  trigger:
  - platform: device
    device_id: 0c8c91866a03868d5f7b465cb3b58bc6
    domain: media_player
    entity_id: media_player.family_room_roonberry
    type: idle
    for:
      hours: 0
      minutes: 20
      seconds: 0
      milliseconds: 0
  condition: []
  action:
  - service: media_player.turn_off
    target:
      entity_id: media_player.family_room_main
  mode: single
- id: '1627140445938'
  alias: Turn on Patio when Roon starts playing
  description: ''
  trigger:
  - platform: device
    device_id: 13411f6cf292ea9c43287209aa355114
    domain: media_player
    entity_id: media_player.patio_roonberry
    type: playing
  condition: []
  action:
  - service: media_player.turn_on
    target:
      entity_id: media_player.patio_2
  - service: media_player.select_source
    data:
      source: aux
    target:
      entity_id: media_player.patio_2
  mode: single
- id: '1638196268480'
  alias: turn off armstrong and getty
  description: ''
  trigger:
  - platform: time
    at: '11:05:00'
  condition:
  - condition: device
    device_id: 3c0d248ed4c6e384bca97d06b9c40f00
    domain: media_player
    entity_id: media_player.family_musiccast_2
    type: is_playing
  action:
  - service: media_player.unjoin
    target:
      entity_id:
      - media_player.patio_musiccast_2
      - media_player.family_musiccast_2
      - media_player.office_musiccast_2
  - service: media_player.turn_off
    target:
      entity_id:
      - media_player.patio_musiccast_2
      - media_player.office_musiccast_2
      - media_player.family_musiccast_2
  mode: single
- id: '1638197847338'
  alias: turn on armstrong and getty
  description: ''
  trigger:
  - platform: time
    at: 07:45:00
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    after: 07:30:00
    before: '11:30:00'
  action:
  - service: media_player.play_media
    target:
      entity_id: media_player.family_room_roonberry
    data:
      media_content_type: channel
      media_content_id: My Live Radio/KSFO 560
  - service: media_player.join
    target:
      entity_id:
      - media_player.family_musiccast_2
    data:
      group_members:
      - media_player.office_musiccast_2
      - media_player.patio_musiccast_2
  - service: hue.hue_activate_scene
    data:
      group_name: master
      scene_name: daytime
  - delay:
      hours: 3
      minutes: 20
      seconds: 0
      milliseconds: 0
  - service: media_player.unjoin
    target:
      entity_id:
      - media_player.office_musiccast_2
      - media_player.family_musiccast_2
      - media_player.patio_musiccast_2
  - service: media_player.media_stop
    target:
      entity_id:
      - media_player.family_musiccast_2
      - media_player.family_room_roonberry
  - service: media_player.turn_off
    target:
      entity_id:
      - media_player.family_musiccast_2
      - media_player.patio_musiccast_2
      - media_player.office_musiccast_2
  mode: single
- id: '1638202864296'
  alias: Family Room - Roon Playing
  description: ''
  trigger:
  - platform: device
    device_id: 0c8c91866a03868d5f7b465cb3b58bc6
    domain: media_player
    entity_id: media_player.family_room_roonberry
    type: playing
  condition: []
  action:
  - service: media_player.turn_on
    target:
      entity_id:
      - media_player.family_musiccast_2
  - service: media_player.select_source
    target:
      entity_id:
      - media_player.family_musiccast_2
    data:
      source: audio3
  mode: single
- id: '1638202983992'
  alias: Patio - Roon Playing
  description: automatically turns stereo on when roon starts playing on patio
  trigger:
  - platform: device
    device_id: 45b2a1d3380ebeba569ba225cea0688a
    domain: media_player
    entity_id: media_player.patio_roonberry
    type: playing
  condition: []
  action:
  - service: media_player.turn_on
    target:
      entity_id:
      - media_player.patio_musiccast_2
  - service: media_player.select_source
    data:
      source: AUX
    target:
      entity_id: media_player.patio_musiccast_2
  mode: single
- id: '1638664013919'
  alias: Harley Bedtime
  description: automatically play classicial music on shuffle at 8:15p, shutting off
    after 3 hours.
  trigger:
  - platform: time
    at: '20:15:00'
    id: trigger-bedtime
  - platform: state
    entity_id: input_boolean.harley_bed
    id: trigger-switch
    from: 'off'
    to: 'on'
  condition:
  - condition: device
    type: is_off
    device_id: 66cb0fbdbab22d7a6f0532e78d5dcf28
    entity_id: switch.family_room_remote_watch_apple_tv
    domain: switch
  - condition: device
    type: is_off
    device_id: 66cb0fbdbab22d7a6f0532e78d5dcf28
    entity_id: switch.family_room_remote_watch_smart_tv
    domain: switch
  action:
  - service: media_player.select_source
    target:
      entity_id: media_player.family_musiccast_2
    data:
      source: audio3
  - service: media_player.play_media
    data:
      media_content_type: playlist
      media_content_id: My Playlists/classical sleep
    target:
      entity_id: media_player.family_room_roonberry
  - service: media_player.shuffle_set
    target:
      entity_id: media_player.family_room_roonberry
    data:
      shuffle: true
  - delay:
      hours: 3
      minutes: 0
      seconds: 0
      milliseconds: 0
  - service: media_player.media_stop
    target:
      entity_id: media_player.family_room_roonberry
  mode: single
- id: '1638932536437'
  alias: someones in the family room
  description: ''
  trigger:
  - type: occupied
    platform: device
    device_id: 3ce104022ae83294d3c1b605541a706f
    entity_id: binary_sensor.family_room_occupancy
    domain: binary_sensor
    for:
      hours: 0
      minutes: 0
      seconds: 10
      milliseconds: 0
  condition:
  - condition: time
    after: 02:00:00
    before: 05:00:00
  action:
  - service: notify.mobile_app_todd_s_phone
    data:
      message: someone is in the family room
      title: motion alert
  - service: tts.google_translate_say
    data:
      entity_id: media_player.master_bedroom_2
      message: 'Alert: someone is in the family room.'
  mode: single
- id: '1640135044966'
  alias: Play Music on Roonberry Downstairs
  description: automation behind the play music switch
  trigger:
  - platform: state
    entity_id: input_boolean.play_music
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: media_player.play_media
    data:
      media_content_id: Playlists/good music
      media_content_type: playlist
    target:
      entity_id: media_player.family_room_roonberry
  - service: media_player.shuffle_set
    target:
      entity_id: media_player.family_room_roonberry
    data:
      shuffle: true
  - service: media_player.join
    target:
      entity_id: media_player.family_musiccast_2
    data:
      group_members:
      - media_player.living_musiccast_2
      - media_player.patio_musiccast_2
  mode: single
- id: '1640136000540'
  alias: Stop Music on Roonberry Downstairs
  description: automation behind the play music switch
  trigger:
  - platform: state
    entity_id: input_boolean.play_music
    to: 'off'
    from: 'on'
  condition: []
  action:
  - service: media_player.media_stop
    target:
      entity_id: media_player.family_room_roonberry
  - service: media_player.unjoin
    target:
      entity_id:
      - media_player.family_musiccast_2
      - media_player.patio_musiccast_2
      - media_player.living_musiccast_2
  mode: single
- id: '1640893822962'
  alias: Turn on TV if Plex starts playing
  description: ''
  trigger:
  - platform: device
    device_id: 4049a3ce523ce1d7af8b5d9f2de5a2a6
    domain: media_player
    entity_id: media_player.plex_plex_for_android_tv_hismarttv_a4
    type: playing
  condition: []
  action:
  - service: media_player.turn_on
    target:
      entity_id: media_player.family_room_tv_3
  - service: media_player.select_source
    target:
      entity_id: media_player.family_room_tv_3
    data:
      source: Plex
  mode: single
- id: '1640893913391'
  alias: Turn Off TV if Plex Turns Off
  description: ''
  trigger:
  - platform: device
    device_id: 4049a3ce523ce1d7af8b5d9f2de5a2a6
    domain: media_player
    entity_id: media_player.plex_plex_for_android_tv_hismarttv_a4
    type: turned_off
  condition: []
  action:
  - service: media_player.turn_off
    target:
      entity_id: media_player.family_room_tv_3
  mode: single
