- id: '1610996669564'
  alias: lights on when paused
  description: Turn on Ambient light on Pause
  trigger:
  - platform: state
    entity_id: media_player.theater_shield
    from: playing
    to: paused
  condition: []
  action:
  - type: turn_on
    device_id: 3e79f994a8b002350491947d33bbb1e5
    entity_id: switch.theater_ambient
    domain: switch
  mode: single
- id: '1610996991686'
  alias: lights off on play
  description: Turn off lights when Media begins to play
  trigger:
  - platform: state
    entity_id: media_player.theater_shield
    to: playing
  condition: []
  action:
  - type: turn_off
    device_id: f12a835a0faa13cb4826f7d38223a344
    entity_id: light.theater_lights_2
    domain: light
  - type: turn_off
    device_id: 3e79f994a8b002350491947d33bbb1e5
    entity_id: switch.theater_ambient
    domain: switch
  mode: single
- id: '1611024383994'
  alias: lights up on stop or idle
  description: Bring lights up to 100% when media is stopped
  trigger:
  - platform: state
    entity_id: media_player.theater_shield
    to: idle
  - platform: state
    entity_id: media_player.theater_shield
    to: 'off'
  condition:
  - condition: not
    conditions:
    - condition: device
      device_id: 7d8e57e35efd5221948d06915e934a4c
      domain: media_player
      entity_id: media_player.plex_plex_for_android_tv_shield_android_tv
      type: is_playing
    - condition: state
      entity_id: media_player.theater_shield
      state: paused
  action:
  - type: turn_on
    device_id: f12a835a0faa13cb4826f7d38223a344
    entity_id: light.theater_lights_2
    domain: light
    brightness_pct: 100
  mode: single
- id: '1611526954610'
  alias: lights on during standby
  description: Bring lights up to 50% when media is paused on Shield
  trigger:
  - platform: state
    entity_id: media_player.theater_shield
    from: playing
    to: standby
  condition:
  - condition: state
    entity_id: light.theater_lights
    state: 'off'
  action:
  - service: light.turn_on
    data:
      entity_id: light.theater_lights
      brightness_pct: 50
  mode: single
- id: '1612398301259'
  alias: lights on during Standby
  description: Turn on Ambient light on Standby
  trigger:
  - platform: state
    entity_id: media_player.theater_shield
    from: playing
    to: standby
  condition: []
  action:
  - type: turn_on
    device_id: 3e79f994a8b002350491947d33bbb1e5
    entity_id: switch.theater_ambient
    domain: switch
  mode: single
- id: '1613889538573'
  alias: set night at 10p
  description: ''
  trigger:
  - platform: time
    at: '22:00'
  condition: []
  action:
  - scene: scene.night_time
  mode: single
- id: '1618764535146'
  alias: Roon in the Office
  description: ''
  trigger:
  - platform: device
    device_id: eb407f8314ed005bf11f3aaa09cbdc8c
    domain: media_player
    entity_id: media_player.office_roonberry
    type: playing
  condition: []
  action:
  - service: media_player.turn_on
    target:
      entity_id: media_player.office_main
  - service: media_player.select_source
    target:
      entity_id: media_player.office_main
    data:
      source: optical
  mode: single
- id: '1618764646815'
  alias: Roon on the Porch
  description: ''
  trigger:
  - platform: device
    device_id: 13411f6cf292ea9c43287209aa355114
    domain: media_player
    entity_id: media_player.patio_roonberry
    type: playing
  condition: []
  action:
  - service: media_player.turn_on
    target:
      entity_id: media_player.patio_main
  - service: media_player.select_source
    data:
      source: aux
    target:
      entity_id: media_player.patio_main
  mode: single
- id: '1618778013049'
  alias: lights off on plex play
  description: ''
  trigger:
  - platform: device
    device_id: b98ccd3b931bd8464397902820797d40
    domain: media_player
    entity_id: media_player.plex_plex_for_android_tv_shield_android_tv
    type: playing
  condition: []
  action:
  - type: turn_off
    device_id: f12a835a0faa13cb4826f7d38223a344
    entity_id: light.theater_lights_2
    domain: light
  - type: turn_off
    device_id: 3e79f994a8b002350491947d33bbb1e5
    entity_id: switch.theater_ambient
    domain: switch
  mode: single
- id: '1618778083115'
  alias: ambient light on plex pause
  description: ''
  trigger:
  - platform: device
    device_id: b98ccd3b931bd8464397902820797d40
    domain: media_player
    entity_id: media_player.plex_plex_for_android_tv_shield_android_tv
    type: paused
  condition:
  - condition: device
    type: is_off
    device_id: f12a835a0faa13cb4826f7d38223a344
    entity_id: light.theater_lights_2
    domain: light
  action:
  - type: turn_on
    device_id: 3e79f994a8b002350491947d33bbb1e5
    entity_id: switch.theater_ambient
    domain: switch
  mode: single
- id: '1626916974326'
  alias: Turn on Stereo when Roon starts playing
  description: ''
  trigger:
  - platform: device
    device_id: df15dcd28b7a749101bec9812d91292f
    domain: media_player
    entity_id: media_player.family_room_stereo
    type: playing
  condition: []
  action:
  - service: media_player.turn_on
    target:
      entity_id: media_player.family_room_main
  - service: media_player.select_source
    target:
      entity_id: media_player.family_room_main
    data:
      source: audio3
  - service: media_player.volume_set
    data:
      volume_level: 0.45
    target:
      entity_id: media_player.family_room_main
  mode: single
- id: '1626917945474'
  alias: Turn Stereo Off when done
  description: Exit theater roonberry activity
  trigger:
  - platform: device
    device_id: 52b18efbc3bfcc2a8d8f4a8b8c94020e
    domain: media_player
    entity_id: media_player.theater_roonberry
    type: turned_off
    id: roon-end-theater
  condition: []
  action:
  - type: turn_off
    device_id: ba50c7a4ef3fb16920ace270971155f2
    entity_id: switch.theater_remote_listen_to_roon
    domain: switch
  mode: single
- id: '1626918072532'
  alias: Roon - Turn on Theater
  description: ''
  trigger:
  - platform: device
    device_id: 14b1a9a958af9876e0dc5087c0940622
    domain: media_player
    entity_id: media_player.theater_roonberry
    type: playing
  condition:
  - condition: device
    type: is_off
    device_id: ba50c7a4ef3fb16920ace270971155f2
    entity_id: switch.theater_remote_play_ps4
    domain: switch
  action:
  - type: turn_on
    device_id: ba50c7a4ef3fb16920ace270971155f2
    entity_id: switch.theater_remote_listen_to_roon
    domain: switch
  mode: single
- id: '1627081584215'
  alias: Turn on mcRack when Roon plays
  description: ''
  trigger:
  - platform: device
    device_id: dd73ebe3c390d6beffb825ee27773501
    domain: media_player
    entity_id: media_player.mcrack
    type: playing
  condition: []
  action:
  - type: turn_on
    device_id: ba50c7a4ef3fb16920ace270971155f2
    entity_id: switch.theater_remote_manage_mediacenter
    domain: switch
  mode: single
- id: '1627081645075'
  alias: Turn off stereo when mcrack stops playing
  description: ''
  trigger:
  - platform: device
    device_id: dd73ebe3c390d6beffb825ee27773501
    domain: media_player
    entity_id: media_player.mcrack
    type: turned_off
  condition: []
  action:
  - type: turn_off
    device_id: ba50c7a4ef3fb16920ace270971155f2
    entity_id: switch.theater_remote_manage_mediacenter
    domain: switch
  mode: single
- id: '1627081929300'
  alias: Turn off Stereo when Roon Stops playing
  description: Auto off in Family Room
  trigger:
  - platform: device
    device_id: 0c8c91866a03868d5f7b465cb3b58bc6
    domain: media_player
    entity_id: media_player.family_room_roonberry
    type: idle
    for:
      hours: 0
      minutes: 20
      seconds: 0
      milliseconds: 0
  condition: []
  action:
  - service: media_player.turn_off
    target:
      entity_id: media_player.family_room_main
  mode: single
- id: '1627140445938'
  alias: Turn on Patio when Roon starts playing
  description: ''
  trigger:
  - platform: device
    device_id: 13411f6cf292ea9c43287209aa355114
    domain: media_player
    entity_id: media_player.patio_roonberry
    type: playing
  condition: []
  action:
  - service: media_player.turn_on
    target:
      entity_id: media_player.patio_2
  - service: media_player.select_source
    data:
      source: aux
    target:
      entity_id: media_player.patio_2
  mode: single
- id: '1638196268480'
  alias: turn off armstrong and getty
  description: ''
  trigger:
  - platform: time
    at: '11:05:00'
  condition:
  - condition: device
    device_id: 3c0d248ed4c6e384bca97d06b9c40f00
    domain: media_player
    entity_id: media_player.family_musiccast_2
    type: is_playing
  action:
  - service: media_player.unjoin
    target:
      entity_id:
      - media_player.patio_musiccast_2
      - media_player.family_musiccast_2
      - media_player.office_musiccast_2
  - service: media_player.turn_off
    target:
      entity_id:
      - media_player.patio_musiccast_2
      - media_player.office_musiccast_2
      - media_player.family_musiccast_2
  mode: single
- id: '1638197847338'
  alias: turn on armstrong and getty
  description: ''
  trigger:
  - platform: time
    at: 07:45:00
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    after: 07:30:00
    before: '11:30:00'
  action:
  - scene: scene.armstrong_and_getty
  - service: media_player.join
    target:
      entity_id:
      - media_player.family_musiccast_2
    data:
      group_members:
      - media_player.office_musiccast_2
      - media_player.patio_musiccast_2
  mode: single
- id: '1638202864296'
  alias: Family Room - Roon Playing
  description: ''
  trigger:
  - platform: device
    device_id: 0c8c91866a03868d5f7b465cb3b58bc6
    domain: media_player
    entity_id: media_player.family_room_roonberry
    type: playing
  condition: []
  action:
  - service: media_player.turn_on
    target:
      entity_id:
      - media_player.family_musiccast_2
  - service: media_player.select_source
    target:
      entity_id:
      - media_player.family_musiccast_2
    data:
      source: audio3
  mode: single
- id: '1638202983992'
  alias: Patio - Roon Playing
  description: automatically turns stereo on when roon starts playing on patio
  trigger:
  - platform: device
    device_id: 45b2a1d3380ebeba569ba225cea0688a
    domain: media_player
    entity_id: media_player.patio_roonberry
    type: playing
  condition: []
  action:
  - service: media_player.turn_on
    target:
      entity_id:
      - media_player.patio_musiccast_2
  - service: media_player.select_source
    data:
      source: AUX
    target:
      entity_id: media_player.patio_musiccast_2
  mode: single
- id: '1638664013919'
  alias: Harley Bedtime
  description: automatically play classicial music on shuffle at 8:15p, shutting off
    after 3 hours.
  trigger:
  - platform: time
    at: '20:15:00'
    id: trigger-bedtime
  condition:
  - condition: device
    type: is_off
    device_id: 66cb0fbdbab22d7a6f0532e78d5dcf28
    entity_id: remote.family_room_remote
    domain: remote
  action:
  - service: media_player.play_media
    data:
      media_content_type: playlist
      media_content_id: Playlists/classical sleep
    target:
      entity_id: media_player.family_room_roonberry
  - service: media_player.shuffle_set
    target:
      entity_id: media_player.family_room_roonberry
    data:
      shuffle: true
  - delay:
      hours: 3
      minutes: 0
      seconds: 0
      milliseconds: 0
  - service: media_player.media_stop
    target:
      entity_id: media_player.family_room_roonberry
  mode: single
