- id: '1610996669564'
  alias: lights on when paused
  description: Turn on Ambient light on Pause
  trigger:
  - platform: state
    entity_id: media_player.theater_shield
    from: playing
    to: paused
  condition: []
  action:
  - type: turn_on
    device_id: 3e79f994a8b002350491947d33bbb1e5
    entity_id: switch.theater_ambient
    domain: switch
  mode: single
- id: '1610996991686'
  alias: lights off on play
  description: Turn off lights when Media begins to play
  trigger:
  - platform: state
    entity_id: media_player.theater_shield
    to: playing
  condition: []
  action:
  - type: turn_off
    device_id: f12a835a0faa13cb4826f7d38223a344
    entity_id: light.theater_lights_2
    domain: light
  - type: turn_off
    device_id: 3e79f994a8b002350491947d33bbb1e5
    entity_id: switch.theater_ambient
    domain: switch
  mode: single
- id: '1611024383994'
  alias: lights up on stop
  description: Bring lights up to 100% when media is stopped
  trigger:
  - platform: state
    entity_id: media_player.theater_shield
    to: idle
  condition:
  - condition: not
    conditions:
    - condition: device
      device_id: 7d8e57e35efd5221948d06915e934a4c
      domain: media_player
      entity_id: media_player.plex_plex_for_android_tv_shield_android_tv
      type: is_playing
    - condition: state
      entity_id: media_player.theater_shield
      state: paused
  action:
  - type: turn_on
    device_id: f12a835a0faa13cb4826f7d38223a344
    entity_id: light.theater_lights_2
    domain: light
    brightness_pct: 100
  mode: single
- id: '1611526954610'
  alias: lights on during standby
  description: Bring lights up to 50% when media is paused on Shield
  trigger:
  - platform: state
    entity_id: media_player.theater_shield
    from: playing
    to: standby
  condition:
  - condition: state
    entity_id: light.theater_lights
    state: 'off'
  action:
  - service: light.turn_on
    data:
      entity_id: light.theater_lights
      brightness_pct: 50
  mode: single
- id: '1612398301259'
  alias: lights on during Standby
  description: Turn on Ambient light on Standby
  trigger:
  - platform: state
    entity_id: media_player.theater_shield
    from: playing
    to: standby
  condition: []
  action:
  - type: turn_on
    device_id: 3e79f994a8b002350491947d33bbb1e5
    entity_id: switch.theater_ambient
    domain: switch
  mode: single
- id: '1613889538573'
  alias: set night at midnight
  description: ''
  trigger:
  - platform: time
    at: 00:00
  condition: []
  action:
  - scene: scene.night
  mode: single
