
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Example configuration.yaml entry
media_player:
#    - platform: androidtv
#      name: Theater Shield
#      host: 192.168.7.81
      
      
#import android TV configuration
media_player android: !include androidtv.yaml
#import musiccast configuration
media_player musiccast: !include musicast.yaml

#4
# X10 Support
mochad:
  host: 192.168.7.21
  port: 1099

#3
# X10 Lights/Switches
light:

light x10: !include mochad.yaml

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
