
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Example configuration.yaml entry
media_player:

#import musiccast configuration
media_player musiccast: !include musicast.yaml

#4
# X10 Support
mochad:
  host: 192.168.7.21
  port: 1099

#3
# X10 Lights/Switches
switch:
  - platform: mochad
    devices:
      - address: m2
        name: Theater Overhead
      - address: m3
        name: Theater Lights
      - address: m4
        name: Equiptment Room
      - address: m8
        name: attic

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
