
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Example configuration.yaml entry
media_player:
# import android TV configuration
#media_player android: !include androidtv.yaml


# radarr sensors
sensor:
  - platform: radarr
    api_key: !secret radarr_key
    host: 192.168.7.30
    port: 8310
    days: 30
    monitored_conditions:
      - upcoming
      - commands
      - status
    
  - platform: nut
    name: Theater Rack UPS
    host: 192.168.7.10
    resources:
      - ups.status.display
      - ups.load
      - input.voltage
      - battery.charge
      - battery.runtime

# sabnzdb 
# sabnzbd: 
#     api_key: 0cd7b12811a84619b10537edeeb3b2f9
#     host: 192.168.7.30 
#     port: 8085

mqtt:
    broker: 192.168.7.20
    username: que
    password: que
    
light:

# Allow UI Customization
homeassistant:
  customize: !include customize.yaml
  
# Custom UI
lovelace:
   mode: storage

  # Added multiple includes for each page in ui-lovelace.yaml
   dashboards:
      lovelace-yaml:
        mode: yaml
        title: Tablets
        icon: "mdi:tablet-dashboard"
        show_in_sidebar: true
        filename: ui-lovelace.yaml
      lovelace-family:
        mode: yaml
        title: Family Room Test
        icon: "mdi:server"
        show_in_sidebar: true
        filename: family-room-remote.yaml

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
