
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Example configuration.yaml entry
media_player:
# import android TV configuration
media_player android: !include androidtv.yaml


# radarr sensors
sensor:
  - platform: radarr
    api_key: !secret radarr_key
    host: 192.168.7.30
    port: 8310
    days: 30
    monitored_conditions:
      - upcoming
      - commands
      - status
    
  - platform: radarr_upcoming_media
    api_key: !secret radarr_key
    host: 192.168.7.30
    port: 8310
    days: 30
    ssl: false
    theaters: false
    max: 10

  - platform: sonarr_upcoming_media
    api_key: !secret sonarr_key
    host: 192.168.7.30
    port: 8989
    days: 7
    ssl: false
    max: 10

  - platform: plex_recently_added
    name: Recently Added Movies # will create sensor.recently_added_movies
    token: !secret plex_token
    host: 192.168.7.97
    port: 32400
    section_types:
      - movie

  - platform: plex_recently_added
    name: Recently Added TV  # will create sensor.recently_added_tv
    token: !secret plex_token
    host: 192.168.7.97
    port: 32400
    section_types:
      - show

  - platform: nut
    name: Theater Rack UPS
    host: 192.168.7.10
    resources:
      - ups.status.display
      - ups.load
      - input.voltage
      - battery.charge
      - battery.runtime

# sabnzdb 
sabnzbd: 
    api_key: 0cd7b12811a84619b10537edeeb3b2f9
    host: 192.168.7.30 
    port: 8085

mqtt:
    broker: 192.168.7.20
    username: que
    password: que
    
light:

# Allow UI Customization
homeassistant:
  customize: !include customize.yaml
  
# Custom UI
lovelace:
   mode: storage

  # Added multiple includes for each page in ui-lovelace.yaml
   dashboards:
      lovelace-yaml:
        mode: yaml
        title: Tablets
        icon: "mdi:tablet-dashboard"
        show_in_sidebar: true
        filename: ui-lovelace.yaml
      lovelace-rack:
        mode: yaml
        title: Server Room
        icon: "mdi:server"
        show_in_sidebar: true
        filename: rack-room.yaml

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
