
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Example configuration.yaml entry
media_player:
  # Theater
  - platform: musiccast_yamaha
    host: 192.168.7.99
    port: 5005

  # Master Bedroom
  - platform: musiccast_yamaha
    host: 192.168.7.100
    port: 5006
    
  # Master Bathroom  
  - platform: musiccast_yamaha
    host: 192.168.7.101
    port: 5007

  # Family Room  
  - platform: musiccast_yamaha
    host: 192.168.7.102
    port: 5008
  
  # Living Room
  - platform: musiccast_yamaha
    host: 192.168.7.103
    port: 5009
    
  # Dining Room
  - platform: musiccast_yamaha
    host: 192.168.7.104
    port: 5010
    
  # Patio  
  - platform: musiccast_yamaha
    host: 192.168.7.105
    port: 5011

  # Pool  
  - platform: musiccast_yamaha
    host: 192.168.7.106
    port: 5012
  
  # Office 
  - platform: musiccast_yamaha
    host: 192.168.7.107
    port: 5013
    
# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
