
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Example configuration.yaml entry
media_player:
# import android TV configuration
media_player android: !include androidtv.yaml
# import musiccast configuration
media_player musiccast: !include musicast.yaml

light:

# Custom UI
lovelace:
   mode: storage

   dashboards:
      lovelace-yaml:
        mode: yaml
        title: Tablets
        icon: "mdi:tablet-dashboard"
        show_in_sidebar: true
        filename: ui-lovelace.yaml

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
