title: Server
views:
  - path: default_view
    title: Server Status
    panel: true
    icon: 'mdi:server'
    cards:
      type: vertical-stack
      cards:
        - type: glance
          entities:
            - entity: sensor.glances_package_id_0_temperature
            - entity: sensor.glances_cpu_load
            - entity: sensor.dasnasty_temperature
            - entity: sensor.dasnasty_cpu_load_averarge_15_min
            - entity: sensor.dasnasty_network_down
            - entity: sensor.dasnasty_network_up
          title: Overview
          show_name: true
          state_color: true
          columns: 6
        - type: history-graph
          entities:
            - entity: sensor.glances_package_id_0_temperature
            - entity: sensor.glances_phy_temperature_temperature
          hours_to_show: 24
          refresh_interval: 0
          title: MediaCenter Rack
        - type: history-graph
          entities:
            - entity: sensor.dasnasty_temperature
            - entity: sensor.dasnasty_volume_1_average_disk_temp
          hours_to_show: 24
          refresh_interval: 0
          title: Dasnasty