title: Home
views:
  - path: default_view
    title: Home
    badges:
      - entity: binary_sensor.updater
      - entity: person.todd
      - entity: person.james
      - entity: person.allison
      - entity: sensor.next_alarm_time
      - entity: sun.sun
    cards:
      - type: weather-forecast
        entity: weather.home
        show_forecast: false
  - title: media
    path: WholeHouseAudio
    icon: 'mdi:audio-video'
    badges:
      - entity: media_player.family_room_main
      - entity: media_player.patio_main
      - entity: media_player.living_room_main
      - entity: media_player.dining_room_main
      - entity: media_player.pool_main
      - entity: media_player.office_main
      - entity: media_player.office_soundbar_main
      - entity: media_player.master_bedroom_main
      - entity: media_player.master_bathroom_main
      - entity: media_player.home_theater_room_main
    cards:
      - type: 'custom:mini-media-player'
        entity: media_player.family_room_main
        artwork: cover
        group: true
        name: Family Room
        hide:
          icon: true
          power_state: false
        speaker_group:
          platform: musiccast_yamaha
          expanded: false
          entities:
            - entity_id: media_player.patio_main
              name: Patio
            - entity_id: media_player.living_room_main
              name: Living Room
            - entity_id: media_player.dining_room_main
              name: Dining Room
            - entity_id: media_player.pool_main
              name: Pool
            - entity_id: media_player.office_main
              name: Office
            - entity_id: media_player.office_soundbar_main
              name: Office Soundbar
            - entity_id: media_player.home_theater_room_main
              name: Theater
            - entity_id: media_player.master_bedroom_main
              name: Master Bedroom
            - entity_id: media_player.master_bathroom_main
              name: Master Bathroom
      - type: 'custom:mini-media-player'
        entity: media_player.patio_main
        artwork: cover
        group: true
        name: Patio
        hide:
          icon: true
          power_state: false
        speaker_group:
          platform: musiccast_yamaha
          expanded: false
          entities:
            - entity_id: media_player.family_room_main
              name: Family Room
            - entity_id: media_player.living_room_main
              name: Living Room
            - entity_id: media_player.dining_room_main
              name: Dining Room
            - entity_id: media_player.pool_main
              name: Pool
            - entity_id: media_player.office_main
              name: Office
            - entity_id: media_player.office_soundbar_main
              name: Office Soundbar
            - entity_id: media_player.master_bedroom_main
              name: Master Bedroom
            - entity_id: media_player.master_bathroom_main
              name: Master Bathroom
            - entity_id: media_player.home_theater_room_main
              name: Theater
      - type: 'custom:mini-media-player'
        entity: media_player.living_room_main
        artwork: cover
        group: true
        name: Living Room
        hide:
          icon: true
          power_state: false
        speaker_group:
          platform: musiccast_yamaha
          expanded: false
          entities:
            - entity_id: media_player.family_room_main
              name: Family Room
            - entity_id: media_player.patio_main
              name: Living Room
            - entity_id: media_player.dining_room_main
              name: Dining Room
            - entity_id: media_player.pool_main
              name: Pool
            - entity_id: media_player.office_main
              name: Office
            - entity_id: media_player.office_soundbar_main
              name: Office Soundbar
            - entity_id: media_player.master_bedroom_main
              name: Master Bedroom
            - entity_id: media_player.master_bathroom_main
              name: Master Bathroom
            - entity_id: media_player.home_theater_room_main
              name: Theater
      - type: 'custom:mini-media-player'
        entity: media_player.office_main
        artwork: cover
        group: true
        name: Office
        hide:
          icon: true
          power_state: false
        speaker_group:
          platform: musiccast_yamaha
          expanded: false
          entities:
            - entity_id: media_player.office_soundbar_main
              name: Office Soundbar
            - entity_id: media_player.family_room_main
              name: Family Room
            - entity_id: media_player.patio_main
              name: Patio
            - entity_id: media_player.living_room_main
              name: Living Room
            - entity_id: media_player.dining_room_main
              name: Dining Room
            - entity_id: media_player.pool_main
              name: Pool
            - entity_id: media_player.master_bedroom_main
              name: Master Bedroom
            - entity_id: media_player.master_bathroom_main
              name: Master Bathroom
            - entity_id: media_player.home_theater_room_main
              name: Theater
            - type: 'custom:mini-media-player'
      - type: 'custom:mini-media-player'
        entity: media_player.office_soundbar_main
        artwork: cover
        group: true
        name: Office
        hide:
          icon: true
          power_state: false
        speaker_group:
          platform: musiccast_yamaha
          expanded: false
          entities:
            - entity_id: media_player.office_main
              name: Office
            - entity_id: media_player.family_room_main
              name: Family Room
            - entity_id: media_player.patio_main
              name: Patio
            - entity_id: media_player.living_room_main
              name: Living Room
            - entity_id: media_player.dining_room_main
              name: Dining Room
            - entity_id: media_player.pool_main
              name: Pool
            - entity_id: media_player.master_bedroom_main
              name: Master Bedroom
            - entity_id: media_player.master_bathroom_main
              name: Master Bathroom
            - entity_id: media_player.home_theater_room_main
              name: Theater
      - type: 'custom:mini-media-player'
        entity: media_player.home_theater_room_main
        artwork: cover
        group: true
        name: Theater
        hide:
          icon: true
          power_state: false
        speaker_group:
          platform: musiccast_yamaha
          expanded: false
          entities:
            - entity_id: media_player.family_room_main
              name: Family Room
            - entity_id: media_player.patio_main
              name: Patio
            - entity_id: media_player.living_room_main
              name: Living Room
            - entity_id: media_player.dining_room_main
              name: Dining Room
            - entity_id: media_player.pool_main
              name: Pool
            - entity_id: media_player.office_main
              name: Office
            - entity_id: media_player.office_soundbar_main
              name: Office Soundbar
            - entity_id: media_player.master_bedroom_main
              name: Master Bedroom
            - entity_id: media_player.master_bathroom_main
              name: Master Bathroom
      - type: 'custom:mini-media-player'
        entity: media_player.master_bedroom_main
        artwork: cover
        group: true
        name: Master Bedroom
        hide:
          icon: true
          power_state: false
        speaker_group:
          platform: musiccast_yamaha
          expanded: false
          entities:
            - entity_id: media_player.master_bathroom_main
              name: Master Bath
            - entity_id: media_player.office_main
              name: Office
            - entity_id: media_player.office_soundbar_main
              name: Office Soundbar
            - entity_id: media_player.patio_main
              name: Patio
            - entity_id: media_player.family_room_main
              name: Family Room
            - entity_id: media_player.living_room_main
              name: Living Room
            - entity_id: media_player.dining_room_main
              name: Dining Room
            - entity_id: media_player.pool_main
              name: Pool
            - entity_id: media_player.home_theater_room_main
              name: Theater
      - type: 'custom:mini-media-player'
        entity: media_player.master_bathroom_main
        artwork: cover
        group: true
        name: Master Bathroom
        hide:
          icon: true
          power_state: false
        speaker_group:
          platform: musiccast_yamaha
          expanded: false
          entities:
            - entity_id: media_player.master_bedroom_main
              name: Master Bedroom
            - entity_id: media_player.office_main
              name: Office
            - entity_id: media_player.office_soundbar_main
              name: Office Soundbar
            - entity_id: media_player.patio_main
              name: Patio
            - entity_id: media_player.family_room_main
              name: Family Room
            - entity_id: media_player.living_room_main
              name: Living Room
            - entity_id: media_player.dining_room_main
              name: Dining Room
            - entity_id: media_player.pool_main
              name: Pool
            - entity_id: media_player.home_theater_room_main
              name: Theater

  - title: Theater
    path: theater
    badges:
      - entity: light.theater_lights_2
      - entity: switch.theater_ambient
      - entity: automation.lights_off_on_play
      - entity: automation.new_automation
      - entity: automation.lights_on_during_standby
      - entity: automation.lights_up_on_stop
    cards:
      - type: media-control
        entity: media_player.theater_shield
      - type: entities
        entities:
          - entity: binary_sensor.theater_occupancy
          - entity: sensor.theater_temperature
      - type: thermostat
        entity: climate.game_room
      - type: entities
        entities:
          - remote.hayfamily
  - title: Family Room
    path: family-room
    badges:
      - entity: binary_sensor.family_room_occupancy
      - entity: sensor.family_room_temperature
      - entity: light.rear_flood_lights
      - entity: light.pool_house_soffits
      - entity: media_player.family_room_main
    cards:
      - type: 'custom:mini-media-player'
        entity: media_player.family_room_main
        artwork: cover-fit
        source: full
        sound_mode: icon
        group: true
        info: short
      - type: thermostat
        entity: climate.dining_room
        name: 'Family Room '
      - type: weather-forecast
        entity: weather.home
        secondary_info_attribute: humidity
        show_forecast: true
